# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

dist: bionic
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get install python3 python3-pip python3-setuptools
  - python3 -VV
  - pip3 install --upgrade pip
  - pip3 -V
  - pip3 install vfb_connect
  - R -e 'install.packages("remotes")'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
