# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
cache: packages

env:
  global:
    - PATH=/opt/python/3.7.1/bin:$PATH

before_install:
  - python -VV
  - python3 -VV
  - pip -V
  - pip3 -V
  - python3 -m pip install vfb_connect
  - R -e 'install.packages("remotes")'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
